(ns eacl.datascript.cljs-test-runner
  (:require [cljs.nodejs :as nodejs]
            [cljs.test :as t]
            [eacl.backend.v8-test]
            [eacl.backend.direct-membership-test]
            [eacl.authorization.batch-test]
            [eacl.authorization.evidence-test]
            [eacl.authorization.evidence-index-test]
            [eacl.authorization.data-test]
            [eacl.authorization.context-test]
            [eacl.authorization.result-test]
            [eacl.authorization.qualification-test]
            [eacl.authorization.qualifier-cache-test]
            [eacl.authorization.temporal-test]
            [eacl.datascript.qualifier-cache-test]
            [eacl.cache.derived-schema-test]
            [eacl.cache.key-test]
            [eacl.cache.standard-lru-test]
            [eacl.cache-test]
            [eacl.caveats.values-test]
            [eacl.caveats.definition-test]
            [eacl.caveats.integrity-test]
            [eacl.caveats.evaluator-test]
            [eacl.datascript.caveat-schema-test]
            [eacl.caveats.plan-test]
            [eacl.caveats.partial-test]
            [eacl.relationships.qualifier-test]
            [eacl.relationships.mutations-test]
            [eacl.core-test]
            [eacl.causal-model-test]
            [eacl.consistency-test]
            [eacl.engine.relationships-test]
            [eacl.engine.scan-cache-test]
            [eacl.engine.stable-route-evidence-test]
            [eacl.engine.stable-reducer-evidence-test]
            [eacl.engine.stable-page-evidence-test]
            [eacl.engine.stable-route-native-evidence-test]
            [eacl.engine.least-path-evidence-test]
            [eacl.operator.seekable-evidence-test]
            [eacl.operator.lookup-evidence-test]
            [eacl.operator.arrow-evidence-test]
            [eacl.datascript.evaluation-clock-test]
            [eacl.datascript.caveat-context-test]
            [eacl.datascript.qualified-check-test]
            [eacl.datascript.qualified-lookup-test]
            [eacl.datascript.qualified-write-test]
            [eacl.caveats.schema-admission-test]
            [eacl.schema.relation-allowance-test]
            [eacl.datascript.qualified-schema-test]
            [eacl.authorization.inspection-test]
            [eacl.datascript.qualified-inspection-test]
            [eacl.client.lookahead-test]
            [eacl.client.range-reuse-test]
            [eacl.datascript.scan-cache-integration-test]
            [eacl.datascript.scan-cache-neutrality-test]
            [eacl.engine.alias-frontier-test]
            [eacl.engine.least-path-portable-test]
            [eacl.engine.sealed-plan-test]
            [eacl.execution-test]
            [eacl.proof-frame-test]
            [eacl.permission-tree-test]
            [eacl.permission-tree-operator-test]
            [eacl.operator.plan-test]
            [eacl.operator.evaluator-test]
            [eacl.operator.bitmask-test]
            [eacl.operator.vector-evaluator-test]
            [eacl.operator.batch-schedule-test]
            [eacl.operator.lookup-test]
            [eacl.operator.feature-gate-test]
            [eacl.operator.recursive-test]
            [eacl.relationships.endpoint-pair-test]
            [eacl.relationships.edge-test]
            [eacl.relationships.upgrade-test]
            [eacl.datascript.qualifier-storage-test]
            [eacl.datascript.migrations.v7-to-v9-test]
            [eacl.relay-test]
            [eacl.request.context-test]
            [eacl.request.counters-test]
            [eacl.secure-format-test]
            [eacl.schema.expression-test]
            [eacl.schema.expression-limits-test]
            [eacl.schema.expression-resolver-test]
            [eacl.schema.expression-graph-test]
            [eacl.schema.expression-fuzz-test]
            [eacl.schema.expression-persistence-test]
            [eacl.schema.expression-policy-test]
            [eacl.spicedb.parser-portability-test]
            [eacl.subproblem-cache-test]
            [eacl.verified-kernel-test]
            [eacl.formal.cache-strategy-adversarial-test]
            [eacl.formal.differential-runner-test]
            [eacl.formal.executed-mutation-controls]
            [eacl.formal.generators-test]
            [eacl.datascript.adapter-certification-test]
            [eacl.datascript.batch-test]
            [eacl.datascript.cache-model-test]
            [eacl.datascript.consistency-v3-test]
            [eacl.datascript.contract-test]
            [eacl.engine.continuation-reuse-test]
            [eacl.engine.stable-page-test]
            [eacl.engine.stable-reducer-test]
            [eacl.datascript.impl-test]
            [eacl.datascript.safe-retraction-test]
            [eacl.datascript.snapshot-lifecycle-test]
            [eacl.datascript.storage-test]))

(nodejs/enable-util-print!)

(defmethod t/report [::t/default :end-run-tests] [m]
  (let [failures (+ (:fail m 0) (:error m 0))]
    (.log js/console
          (str "EACL DataScript CLJS tests complete. failures="
               (:fail m 0)
               " errors="
               (:error m 0)))
    (js/process.exit failures)))

(defn -main []
  (t/run-tests 'eacl.backend.v8-test
               'eacl.backend.direct-membership-test
               'eacl.authorization.batch-test
               'eacl.authorization.evidence-test
               'eacl.authorization.evidence-index-test
               'eacl.authorization.data-test
               'eacl.authorization.context-test
               'eacl.authorization.result-test
               'eacl.authorization.qualification-test
               'eacl.authorization.qualifier-cache-test
               'eacl.authorization.temporal-test
               'eacl.datascript.qualifier-cache-test
               'eacl.cache.derived-schema-test
               'eacl.cache.key-test
               'eacl.cache.standard-lru-test
               'eacl.cache-test
               'eacl.core-test
               'eacl.causal-model-test
               'eacl.consistency-test
               'eacl.engine.relationships-test
               'eacl.engine.scan-cache-test
               'eacl.engine.stable-route-evidence-test
               'eacl.engine.stable-reducer-evidence-test
               'eacl.engine.stable-page-evidence-test
               'eacl.engine.stable-route-native-evidence-test
               'eacl.engine.least-path-evidence-test
               'eacl.operator.seekable-evidence-test
               'eacl.operator.lookup-evidence-test
               'eacl.operator.arrow-evidence-test
               'eacl.datascript.evaluation-clock-test
               'eacl.datascript.caveat-context-test
               'eacl.datascript.qualified-check-test
               'eacl.datascript.qualified-lookup-test
               'eacl.datascript.qualified-write-test
               'eacl.caveats.schema-admission-test
               'eacl.schema.relation-allowance-test
               'eacl.datascript.qualified-schema-test
               'eacl.authorization.inspection-test
               'eacl.datascript.qualified-inspection-test
               'eacl.client.lookahead-test
               'eacl.client.range-reuse-test
               'eacl.datascript.scan-cache-integration-test
               'eacl.datascript.scan-cache-neutrality-test
               'eacl.engine.alias-frontier-test
               'eacl.engine.least-path-portable-test
               'eacl.engine.sealed-plan-test
               'eacl.execution-test
               'eacl.proof-frame-test
               'eacl.permission-tree-test
               'eacl.permission-tree-operator-test
               'eacl.operator.plan-test
               'eacl.operator.evaluator-test
               'eacl.operator.bitmask-test
               'eacl.operator.vector-evaluator-test
               'eacl.operator.batch-schedule-test
               'eacl.operator.lookup-test
               'eacl.operator.feature-gate-test
               'eacl.operator.recursive-test
               'eacl.relationships.endpoint-pair-test
               'eacl.relationships.edge-test
               'eacl.relationships.upgrade-test
               'eacl.datascript.qualifier-storage-test
               'eacl.datascript.migrations.v7-to-v9-test
               'eacl.relay-test
               'eacl.request.context-test
               'eacl.request.counters-test
               'eacl.secure-format-test
               'eacl.caveats.values-test
               'eacl.caveats.definition-test
               'eacl.caveats.integrity-test
               'eacl.caveats.evaluator-test
               'eacl.datascript.caveat-schema-test
               'eacl.caveats.plan-test
               'eacl.caveats.partial-test
               'eacl.relationships.qualifier-test
               'eacl.relationships.mutations-test
               'eacl.schema.expression-test
               'eacl.schema.expression-limits-test
               'eacl.schema.expression-resolver-test
               'eacl.schema.expression-graph-test
               'eacl.schema.expression-fuzz-test
               'eacl.schema.expression-persistence-test
               'eacl.schema.expression-policy-test
               'eacl.spicedb.parser-portability-test
               'eacl.subproblem-cache-test
               'eacl.verified-kernel-test
               'eacl.formal.cache-strategy-adversarial-test
               'eacl.formal.differential-runner-test
               'eacl.formal.executed-mutation-controls
               'eacl.formal.generators-test
               'eacl.datascript.adapter-certification-test
               'eacl.datascript.batch-test
               'eacl.datascript.cache-model-test
               'eacl.datascript.consistency-v3-test
               'eacl.datascript.contract-test
               'eacl.engine.continuation-reuse-test
               'eacl.engine.stable-page-test
               'eacl.engine.stable-reducer-test
               'eacl.datascript.impl-test
               'eacl.datascript.safe-retraction-test
               'eacl.datascript.snapshot-lifecycle-test
               'eacl.datascript.storage-test))

(set! *main-cli-fn* -main)
